baseURL = "https://daronadams.github.io/dcadams-blog/"
title = "Journey Before Destination"
theme = "PaperMod"

[params]
defaultTheme = "auto"
ShowCodeCopyButtons = true
ShowReadingTime = true

[params.homeInfoParams]
Title = "Hey, I'm Daron"
Content = "Software engineer at Amazon. Building things with distributed systems, Rust, and graphics programming in my free time."

[[params.socialIcons]]
name = "github"
url = "https://github.com/DaronAdams"

[[params.socialIcons]]
name = "linkedin"
url = "https://linkedin.com/in/daron-adams"

[[menu.main]]
name = "Blog"
url = "/posts/"
weight = 1

[[menu.main]]
name = "Resume"
url = "/resume.pdf"
weight = 2

[[menu.main]]
name = "Resources"
url = "/resources/"
weight = 3

